### ISSUE TITLE
problem version

### ISSUE THREAD

**Issue by AX-NICOLAS** [peterturza/gitlab-ci-android-fastlane#1]
* What went wrong:
A problem occurred configuring project ':app'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Build-Tools 26.0.1, Android SDK Platform 26].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

compileSdkVersion 26
buildToolsVersion "26.0.1"

Can you fix the problem ? 

I don't understand how fix the problem.

Cheers,

**Comment by peterturza** [comment]
Project was moved, please use image from new location `unitedclassifiedsapps/gitlab-ci-android-fastlane:1.0.2`. This issue was fixed in tag `1.0.2`. Project was moved to https://github.com/unitedclassifiedsapps/gitlab-ci-android-fastlane
